//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.authors = new HashSet<author>();
            this.genres = new HashSet<genre>();
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string isbn { get; set; }
        public string edition { get; set; }
        public string description { get; set; }
        public byte[] data { get; set; }
        public int added_by { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> rate { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<author> authors { get; set; }
        public virtual ICollection<genre> genres { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
