//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class book
    {
        public book()
        {
            this.authors = new HashSet<author>();
            this.genres = new HashSet<genre>();
            this.users = new HashSet<user>();
        }

        public int id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessageResourceType = (typeof(Localization.Error)), ErrorMessageResourceName = "TitleRequired")]
        public string title { get; set; }


        [Display(Name = "ISBN")]
        [Required(ErrorMessageResourceType = (typeof(Localization.Error)), ErrorMessageResourceName = "ISBNRequired")]
        public string isbn { get; set; }
        public string edition { get; set; }
        public string description { get; set; }
        public byte[] data { get; set; }

        [Display(Name = "User")]
        [Required(ErrorMessageResourceType = (typeof(Localization.Error)), ErrorMessageResourceName = "UserAddedRequired")]
        public int added_by { get; set; }
        public Nullable<bool> active { get; set; }

        public virtual user user { get; set; }
        public virtual ICollection<author> authors { get; set; }
        public virtual ICollection<genre> genres { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}