//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.authors = new HashSet<author>();
            this.genres = new HashSet<genre>();
            this.users = new HashSet<user>();
        }

        [ScaffoldColumn(false)]
        public int id { get; set; }

        [DisplayName("Title")]
        [Required(ErrorMessageResourceType = (typeof(Localization.Error)), ErrorMessageResourceName = "TitleRequired"), StringLength(50)] 
        public string title { get; set; }

        [DisplayName("ISBN")]
        public string isbn { get; set; }

        [DisplayName("Edition")]
        public string edition { get; set; }

        [DisplayName("Description")]
        public string description { get; set; }

        [DisplayName("Data")]
        public byte[] data { get; set; }


        [DisplayName("User")]
        [Required(ErrorMessageResourceType = (typeof(Localization.Error)), ErrorMessageResourceName = "UserRequired")] 
        public int added_by { get; set; }

        [DisplayName("Active")]
        [Required(ErrorMessageResourceType = (typeof(Localization.Error)), ErrorMessageResourceName = "ActiveRequired")] 
        public Nullable<bool> active { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<author> authors { get; set; }
        public virtual ICollection<genre> genres { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
