//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public genre()
        {
            this.books = new HashSet<book>();
        }

        [ScaffoldColumn(false)]
        public int id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Name is required"), StringLength(50)] 
        public string name { get; set; }

        [DisplayName("active")]
        [Required]
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<book> books { get; set; }
    }
}
